### ISSUE TITLE
Make capitalization optional

### ISSUE THREAD

**Issue by gpion** [WetHat/OnenoteTaggingKit#1]
Tags are automatically renamed with an initial capital letter.
Could it be made optional?

**Comment by WetHat** [comment]
I'll make this configurable in the next release

**Comment by WetHat** [comment]
Fixed in V3.3

**Comment by muguu** [comment]
will CamelCase be possible then as well?

**Comment by WetHat** [comment]
Hi muguu,
If you select _As Entered_ in the _Tag Options_, camel case is possible too. However, camel case will not be enforced. The tags are used exactly as you typed them in. Please see the [Preferences Tab](https://github.com/WetHat/OnenoteTaggingKit/wiki/Preferences-Tab) wiki page for details.


WetHat
