### ISSUE TITLE
hope to make OnenoteTaggingKit for uwp version

### ISSUE THREAD

**Issue by zhongguocn** [WetHat/OnenoteTaggingKit#14]
Thanks for this good stuff，
Can you make the OnenoteTaggingKit for uwp version？

**Comment by WetHat** [comment]
Hi zhongguocn ,

Currently it is not possible to write add-ins for the UWP version. This may change in the future. Ass soon as Add-ins are supported I'll take look at the possibility to port the tagging kit to the UWP version.

WetHat

**Comment by zhongguocn** [comment]
Thank you very much!



发自我的小米手机
在 Peter Ernst <notifications@github.com>，2018年7月23日 下午5:13写道：

Hi zhongguocn ,

Currently it is not possible to write add-ins for the UWP version. This may change in the future. Ass soon as Add-ins are supported I'll take look at the possibility to port the tagging kit to the UWP version.

WetHat
