### ISSUE TITLE
Is there anyway to add Page tags programmatically?

### ISSUE THREAD

**Issue by nicholsonma** [WetHat/OnenoteTaggingKit#15]
I am writing a program to convert data from another program into OneNote pages.  I need to add page tags to them and want to know if there is anyway to do it programmatically.   I am thinking there is not but wanted to check.  I am using the API provided by Microsoft.Office.Interop.OneNote.  Thanks!

**Comment by WetHat** [comment]
Hi nicholsonma,

The Tagging Kit uses the API Microsoft.Office.Interop.OneNote to implement Page Tags. So in principle you would be able to add Page Tags yourself, if you knew what it takes to build Page Tags.
I would suggest to look into the Tagging Kit sources to learn how to construct Page Tags and extract the relevant code for use in your own code.

WetHat
