### ISSUE TITLE
Allow tagging on bottom page or hiding tag text (for text previews to work)

### ISSUE THREAD

**Issue by frogger72** [WetHat/OnenoteTaggingKit#16]
Currently, the tag is at the top of the page which makes the list view preview just show the tag name. This makes looking for notes in the list view really hard if you have a lot of tagged notes. Also, if you are searching for a tag, there is no way to distinguish between the notes in the list view other than opening each one. Is there a workaround?

**Comment by WetHat** [comment]
Hi frogger72,

I think I can make this configurable

**Comment by zhongguocn** [comment]
> Hi frogger72,
> 
> I think I can make the placement of the tags configurable.
> 
> WetHat

I look forward for the new version.thanks

**Comment by frogger72** [comment]
> Hi frogger72,
> 
> I think I can make the placement of the tags configurable.
> 
> WetHat

That would be great. Thanks!

**Comment by WetHat** [comment]
This new feature is documented in [Find Notes by Tags](https://github.com/WetHat/OnenoteTaggingKit/wiki/Find-Notes-by-Tags)

**Comment by WetHat** [comment]
@all-contributors add @ghost  for ideas
