### ISSUE TITLE
Unable to see Add in of Onenote tagging kit

### ISSUE THREAD

**Issue by SaratBushan** [WetHat/OnenoteTaggingKit#18]
Hi

I have installed latest version of Onenote Tagging Kit. But  i am not able to view the add in. When I see in Quick Access tool bar on Onenote  I see the  add in has been disabled

I do not know how to enable the add in.  Please guide me

Thanks
Sarat

**Comment by WetHat** [comment]
Please check out the these instructions: [Tagging Kit Not Shown in Ribbon](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-Kit-Not-Shown-in-Ribbon)

.. and please let me know if they solved our problem.


WetHat

**Comment by SaratBushan** [comment]
Hi

It worked. We had to do few different actions though as shown in the attachment
![add in](https://user-images.githubusercontent.com/42663248/48683678-5a935800-ebd4-11e8-8bac-1942e68bdfcd.jpg)

Go to Ribbon - More commands- Add-ins.. From dropdown of Manage.. Select Disabled items.
Click the enable option. The add in will now be seen in the tool bar.

Thanks for help

Sarat
