### ISSUE TITLE
Installation without admin rights

### ISSUE THREAD

**Issue by anayeri** [WetHat/OnenoteTaggingKit#19]
Is there a possibility to install the addin without admin rights? The current releases require admin rights and convincing corporate IT teams that this very useful plugin is safe is next to impossible.

**Comment by WetHat** [comment]
Hi anayeri,

I fully understand the concerns of your corporate IT. Unfortunately the OneNote desktop Add-in infrastructure requires add-ins to be registered COM components. This registration requires admin rights. Currently I see no way to create a non-admin installation.

WetHat
