### ISSUE TITLE
Feature Request: Apply tag to Search Results

### ISSUE THREAD

**Issue by PrismElixir** [WetHat/OnenoteTaggingKit#2]
Allow applying tags to the pages found by the Search (CTRL-E) results.

Or provide a way to search Pages within your tool.

**Comment by WetHat** [comment]
Currently a simple method to tag search results with a special token is available. This special tag then then be renamed in the settings dialog. This is a bit clumsy and should be replaced by a proper tagging dialog.

**Comment by WetHat** [comment]
Please see documentation at: [Find Notes by Tags](https://github.com/WetHat/OnenoteTaggingKit/wiki/Find-Notes-by-Tags)

WetHat
