### ISSUE TITLE
Enhance the tag organization features

### ISSUE THREAD

**Issue by thefujunjie** [WetHat/OnenoteTaggingKit#20]
This is a great plugin for Onenote!
I was almost about to stop using onenote before I finnally found this very very useful plugin. Thank you so much!
Up to now, it works perfectly for me to tag pages and search by tags.
I would suggest the further enhancement of the tag organization features of this plugin. For example, allow us to categorize tags into different groups, sort tags in different ways, search tags using AND/OR logic, and so on. 
Thanks again for making it possible for me to continue using onenote :-)

**Comment by bmxbmx3** [comment]
> This is a great plugin for Onenote!
> I was almost about to stop using onenote before I finnally found this very very useful plugin. Thank you so much!
> Up to now, it works perfectly for me to tag pages and search by tags.
> I would suggest the further enhancement of the tag organization features of this plugin. For example, allow us to categorize tags into different groups, sort tags in different ways, search tags using AND/OR logic, and so on.
> Thanks again for making it possible for me to continue using onenote :-)
A good idea,and I think it needs more to enhance itself,for example:
- if this plugin can automatically summarize some tags called keywords from the context or the title,show them and be deleted selectively by you.
- When you want to add tags,this plugin can make associations through previous tags but not just characters matching,and give some advice about which tags can serve you best.
-Add some shortcut keys to quickly add and delete tags.
That's it.I hope this good plugin will be found by more people.

**Comment by WetHat** [comment]
Hi @thefujunjie,

Some limited way to simulate or conditions is described here: [Find Related Notes](https://github.com/WetHat/OnenoteTaggingKit/wiki/Find-Related-Notes)

**Comment by WetHat** [comment]
Hi @thefujunjie ,

Keyboard shortcuts to add/delete tags are described here: [Tagging a Page](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-a-Page)

**Comment by WetHat** [comment]
* Hashtags can be _imported_ from page content. Imported tags are fully functional in search and search results can be saved and updated on OneNote pages since the previous release.
* Additional search filters (OR, NOT) methods were added in [Release v5.0.8424](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v5.0.8424).

I would say this concludes this issue.
