### ISSUE TITLE
[Feature Request] List tasks within tagged pages

### ISSUE THREAD

**Issue by muguu** [WetHat/OnenoteTaggingKit#23]
This is based on this idea but with another focus: [https://github.com/WetHat/OnenoteTaggingKit/issues/10](url)

**My use case**
When I write meeting minutes, I usually add tasks within these minutes by applying the
task tick box to a text within OneNote

**My request**
Provide an additional option within Find Pages to list the tasks within the pages found according to the tags.

**Comment by WetHat** [comment]
Fixed in this [feature release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.8.7617)
