### ISSUE TITLE
No menu item will be created after 3.7.7551 installed

### ISSUE THREAD

**Issue by jeffreyren** [WetHat/OnenoteTaggingKit#30]
I tried 3.7.7551 and found no menu item will be created in OneNote.
I tried overwriting old version (3.7.7393) or uninstalling old version first, and the result were the same.
If I install 3.7.7393, everything is good.

This is from old version 3.7.7393.
![image](https://user-images.githubusercontent.com/19634486/92982465-9e5dfc80-f4e1-11ea-8747-7bf8b76b1f62.png)

Windows 10 Chinese, OneNote 2016 Chinese v16.0.13127.20402, 64-bit
Could you please check this issue?
Thanks.

**Comment by WetHat** [comment]
Hi @jeffreyren,

I was unable to reproduce this issue. Could you please make a little experiment for me?

1. Exit OneNote
2. Upgrade the tagging kit by running the installer [SetupTaggingKitWiX3.7.7551.20257.msi](https://github.com/WetHat/OnenoteTaggingKit/releases/download/v3.7/SetupTaggingKitWiX3.7.7551.20257.msi)
3. Start OneNote and check if the menu items are present.
4. If the menu items are **still missing** please follow the instructions on the Wiki page [Tagging Kit Not Shown in Ribbon](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-Kit-Not-Shown-in-Ribbon).

Any luck with the menu items showing?

**Comment by jeffreyren** [comment]
Hi @WetHat,
I tried, but it seems still disappeared in 3rd step and 4th step.
I have already confirmed the onenote instance was closed first.
![image](https://user-images.githubusercontent.com/19634486/93962306-e90f2c80-fd9d-11ea-85e1-a09d94958c0f.png)

No add-in was found.
Note my system and onenote are chinese x64 version, maybe something is different with English version.

Thanks.

**Comment by WetHat** [comment]
Hi @jeffreyren,

I've created an experimetal installer to address the installation isssue: [SetupTaggingKitWiX.3.7.7571.20274.zip](https://github.com/WetHat/OnenoteTaggingKit/files/5267065/SetupTaggingKitWiX.3.7.7571.20274.zip).

Would you mind trying that out?

Thanks.

**Comment by jeffreyren** [comment]
Hi @WetHat,
Yes, this installer works and the menu appeared as expected.
Thanks.

**Comment by zhongguocn** [comment]
Version 3.7.7571.20274 is installed and the menu is displayed correctly.

thank you!


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Peter Ernst<mailto:notifications@github.com>
发送时间: 2020年9月23日 17:34
收件人: WetHat/OnenoteTaggingKit<mailto:OnenoteTaggingKit@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [WetHat/OnenoteTaggingKit] No menu item will be created after 3.7.7551 installed (#30)


Hi @jeffreyren<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeffreyren&data=02%7C01%7C%7Cb4de7d7b64364e13245808d85fa3dd45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637364504675366061&sdata=YdYZx6WonpiLpcd0An523i6G3S67gTNDpiSx551%2FxiE%3D&reserved=0>,

I've created an experimetal installer to address the installation isssue: SetupTaggingKitWiX.3.7.7571.20274.zip<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWetHat%2FOnenoteTaggingKit%2Ffiles%2F5267065%2FSetupTaggingKitWiX.3.7.7571.20274.zip&data=02%7C01%7C%7Cb4de7d7b64364e13245808d85fa3dd45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637364504675376045&sdata=IH33fSetcm88xVKaHX%2BsKmzOd%2FRGV0AnJybCCUhJeYA%3D&reserved=0>.

Would you mind trying that out?

Thanks.

―
