### ISSUE TITLE
Support for Arabic

### ISSUE THREAD

**Issue by osman1963** [WetHat/OnenoteTaggingKit#31]
Great work  :) 
May i just suggest addding full Arabic support. For now the add-on accepts adding tags in Arabic perfectly. However, when I wanted to copy the tags to another machine, using the way you recommended the English tags appeared normally but the Arabic ones were replaced by question marks. Or is there a trick I don't know of to copy the tags preserving the Arabic ones. Any help is appreciated.. and keep up the great work.

Thanks in advance

**Comment by osman1963** [comment]
This issue could be solved by continuously syncing the notebooks using ON 2016

**Comment by WetHat** [comment]
Hi osman1963,

good to hear that you found a solution. Nevertheless there is a bug in the copy to clipboard code which I was able to reproduce,
