### ISSUE TITLE
Search functionality non functional on Windows on ARM Onenote Client

### ISSUE THREAD

**Issue by iaponte** [WetHat/OnenoteTaggingKit#32]
Tags are not searchable on Surface Pro X running Onenote 2016 with add in. Tags can be generated and added to page but search functionality is not available

Willing to work with developer to resolve should developer not have access to windows on ARM device

Attached below is logfile results
INFO: Register (171) | OneNote Tagging Kit logging activated.
	Addin-Version: 3.7.7581.19466
	.net Framework Version: 4.0.30319.42000
	Configuration: Release
INFO: OnConnection (92) | Connection mode 'ext_cm_Startup'
INFO: .ctor (32) | OneNote application proxy constructed successfully
INFO: Run (50) | Background tagging service started
INFO: OnAddInsUpdate (57) | OneNote Tagging Kit update initiated; Arguments ''
INFO: GetCustomUI (164) | UI configuration requested: Microsoft.OneNote
INFO: OnStartupComplete (142) | Startup Arguments ''
INFO: OneNoteSchema (180) | Using current notebook to determine OneNote version
INFO: OneNoteSchema (197) | OneNote schema version is xs2013
INFO: OnStartupComplete (150) | OneNote Tagging Kit initialization complete!
INFO: editTags (176) | Show tag editor
INFO: GetHierarchy (275) | Start Node = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{E19553782173991367816420152958895765810320951}; Scope = hsSelf
INFO: ExtractTags (183) | Extracted 0 tags from 1 pages.
INFO: EnqueuePagesForTagging (204) | 1 page(s) enqueued for tagging with '#gettingstarted' using UNITE
INFO: findTags (185) | Show tag finder
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPages (232) | query=gettingstarted; Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPages (232) | query=gettingstarted; Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: GetHierarchy (275) | Start Node = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{E19553782173991367816420152958895765810320951}; Scope = hsSelf
INFO: ExtractTags (183) | Extracted 1 tags from 1 pages.
INFO: FindPages (232) | query=gettingstarted; Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPages (232) | query=example linked page; Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPages (232) | query=example linked page; Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: findTags (185) | Show tag finder
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: GetHierarchy (275) | Start Node = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{E1947159144667263058081944956308611207277061}; Scope = hsSelf
INFO: ExtractTags (183) | Extracted 0 tags from 1 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: GetHierarchy (275) | Start Node = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{B0}; Scope = hsPages
INFO: ExtractTags (183) | Extracted 1 tags from 2 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: GetHierarchy (275) | Start Node = {AEEB9B89-7654-48E3-8560-8C98BC4971F4}{1}{B0}; Scope = hsPages
INFO: ExtractTags (183) | Extracted 1 tags from 2 pages.
INFO: findTags (185) | Show tag finder
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = {5C8D2E30-D649-47FB-BC16-FD4C100635DD}{1}{B0}; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: manageTags (194) | Show settings editor
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: findTags (185) | Show tag finder
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: FindPagesByMetadata (254) | Scope = ; metaKey = TaggingKit.PageTags
INFO: ExtractTags (183) | Extracted 0 tags from 0 pages.
INFO: manageTags (194) | Show settings editor

**Comment by WetHat** [comment]
Hi @iaponte,

Do you have the *Windows Search Service* turned off on your _Surface_ laptop? There is also a chance of an incompatibility of the add-in on ARM devices.

Please turn **off** the _Windows Search Service_ integration  on the _Tagging Kit_ _Settings_ dialog as described in [Tag or Full Text Queries do not work](https://github.com/WetHat/OnenoteTaggingKit/wiki/Searching-pages-by-Tags-or-Full-Text-Queries-does-not-work).

The fallback search implementation is slower the _Windows Search Service_ but has a chance to get _some_ search functionality back

Please let me know what you find out so that we can take it from there.

**Comment by iaponte** [comment]
Fixed the issue, for now at least. I'll let you know if anything else comes up
