### ISSUE TITLE
Also add Custom Tags to Page Tags to improve search with add-in's Find Pages and OneNote's built-in seach

### ISSUE THREAD

**Issue by JohnEricson** [WetHat/OnenoteTaggingKit#35]
Thanks for a great add-in. I use tags to be able to more easily find my pages on OneNote Desktop and OneNote for Android. I need to be able to search for several tags at the same site. For example both the tags Important and Question. This works well with your "Find Pages" function when they are Page tags, but it doesn't work when it's OneNotes built-in Custom tagged paragraphs in the pages text.

As I have a lot of my pages tagged using Custom tags, and I like to tag the specific information such as text, pictures or videos I would like these to be added to the Page tags field as well, so the tag's name gets searchable both using your Find Pages function as well as the built-in free text search in OneNote Desktop and OneNote for Android.

![image](https://user-images.githubusercontent.com/946327/96424849-950c3200-11fb-11eb-9830-ad7d3a6825e9.png)

Here is a picture showing what I mean. Text _"Tagged text 1"_ is tagged with the _"Important"_ Custom tag and same for _"Tagged text2"_. When I update Page tags on the page using the add-in's Tag Pages window I would like these to be added to the "Page Tags" field as well.

So I would really like to see such an improvement added to your add-in. Perhaps this can be added to the background job that is spawned when you change Page tags on a page? The solution could perhaps work the same as you suggested in this https://github.com/WetHat/OnenoteTaggingKit/issues/29#issuecomment-686412599 comment . Perhaps it might be a good idea to have a preference option to toggle this behavior in the add-in's Settings?

Do you think this is solvable?

**Comment by WetHat** [comment]
Hi @JohnEricson,

_Do you think this is solvable?_

To some degree. Unfortunately, the OneNote API does not support page change events (or in fact any events), so spawning background jobs to search pages for tags on change is out of reach.  However, if a manual approach which is like the process described in issue #29 would be acceptable then something can be done.  Here's an updated proposal:

1. Extend the _Settings_ dialog to configure content scanning OneNote pages for:
   * OneNote tags (built-in or custom)
   * Hashtags in page text
2. Add options to configure how scanned content is processed:
    1. Scanned content (OneNote tags & hashtags) is added to the suggestions via `Presets --> Tags from Current Page`.
        This is the method suggested in Issue #29. To add the tags to the OneNote page it would be necessary to
        press `Enter` on the input field and then subsequently apply the tags to the page manually.
    2. Scanned content from the current page is **automatically** added to the _Tags_ panel of the _Tag Pages_ dialog, so that it 
        would get added as page tags along with the other tags the user might have entered. 

I wonder if 2.i (adding scanned page content to suggestions) is useful. Maybe implementing just 2.ii would suffice. 

What do you think?

**Comment by JohnEricson** [comment]
> I wonder if 2.i (adding scanned page content to suggestions) is useful. Maybe implementing just 2.ii would suffice.

For me 2.ii would suffice fine, as I'm mostly using OneNote's Tags-menu to do my tagging and then use the _Tag Pages_ dialog to update my pages.

As I mostly tag a lot of pages at the same time using the _Selected Pages_ or _Current Section_ options in the _Tag Pages_ dialog I think it would be more useful for me if the scanned content from the current page is not automatically added to the _Tags_ panel, but instead the scanning and adding is performed in the background job on each page.

Let me clarify. The reason I think this is that I have one tag used on every page in the same section, and then I add extra different tags in the content on each page.  So with my preferred solution I could then very easily just refresh the page tags on all pages in a section, by in the _Tag Pages_ dialog picking the Suggested tag used on all pages in the section and then chose _Current Section_ and then press the Add button, and this would refresh all my pages.

If tags were automatically added to the Tags panel I'm unsure how it would work with changing several pages at the same time.

Actually UI wise I think just having a _Refresh_ button that would run the background job on all selected pages would suffice fine for me as a work around for the missing page change event in OneNote's API.

**Comment by WetHat** [comment]
I now understand what you are aiming at. In your use model you want to _import_ OneNote tags, but they would not be
_first class citizens_ in the page tag system. 

_Imported_ OneNote Tags would:
* be displayed along with page tags on OneNote pages
* would participate in facetted search

_Imported_ OneNote Tags would **not**:
* be editable (add / remove) by the Tagging Kit. If OneNote tags change (by means of the built-in Tag functionality) they have
  to be _re-imported_.
* Would not appear as tags suggestions (because they do not _belong_ to the Tagging Kit system).

For _imported_ Tags to be distinguishable from regular page tags they need to be marked somehow. I would suggest
appending text markers (emoji) like so:

![image](https://user-images.githubusercontent.com/10697674/96842275-21616380-144d-11eb-8916-138b27a89c56.png)

**1** are _imported_ OneNote tags, **2** are regular page tags.

With text markers **pre-pended**, all imported tags would be kept together:
![image](https://user-images.githubusercontent.com/10697674/96845458-0690ee00-1451-11eb-8516-c91d99e1e366.png)

In the _Find Tagged Pages_ dialog _imported_ OneNote Tags would show up like so:

![image](https://user-images.githubusercontent.com/10697674/96842848-d6941b80-144d-11eb-82d4-823469934d8c.png)

Finally, _imported_ OneNote tags would need to be updated manually by executing a _resync_ action of the _Tag Pages_ dialog

![image](https://user-images.githubusercontent.com/10697674/96844275-99c92400-144f-11eb-9a19-bba3df7d4886.png)

Is this anything you can relate to?

**Comment by JohnEricson** [comment]
That looks spot on! That looks like a really good way to solve it and it would fulfill my needs perfectly because then I can easily search for my tags (even several of them at the same time) in all OneNote applications.

Especially the _Resync_ button is a great addition as it allows to quickly resync several pages in one click.

My only suggestion would be to perhaps try to incorporate a resync symbol more similar to web browsers or other sync programs, such as for example this one:

![image](https://user-images.githubusercontent.com/946327/96850839-989bf500-1457-11eb-9f57-07b45f397104.png)
(source: http://getdrawings.com/refresh-icon-png-transparent#refresh-icon-png-transparent-67.png)

so it's more familiar and predictable to the user. Apart from that, looks excellent!

**Comment by WetHat** [comment]
Hi @JohnEricson,

I've implemented the functionality, but still need to sort out Chinese translation and other documentation tasks. If you would like to test the new features now, please install the beta version of the Tagging Kit:
[SetupTaggingKitWiX.3.8.7607.24792.zip](https://github.com/WetHat/OnenoteTaggingKit/files/5458435/SetupTaggingKitWiX.3.8.7607.24792.zip)

To turn on the new features you need to open the _Settings_ dialog and check OneNote Tag import .

Let me know what you think?

**Comment by JohnEricson** [comment]
Excellent news @WetHat!

I'll try to take a look at it later today.

**Comment by JohnEricson** [comment]
I've installed it now and tested it. It works just like I wanted. The function to just refresh all the tags in a section works great and it has greatly improved how I can work with my tags. I tested to search for multiply tags in both OneNote Desktop and OneNote for Android and it works super. Now I can much easier find that specific note on my phone when I'm on the go 😄

Thank you very much for your work! It's much appreciated! I found no bugs or issues so I would consider this issue solved with this version.

**Comment by zhongguocn** [comment]
> Hi @JohnEricson,
> 
> I've implemented the functionality, but still need to sort out Chinese translation and other documentation tasks. If you would like to test the new features now, please install the beta version of the Tagging Kit:
> [SetupTaggingKitWiX.3.8.7607.24792.zip](https://github.com/WetHat/OnenoteTaggingKit/files/5458435/SetupTaggingKitWiX.3.8.7607.24792.zip)
> 
> To turn on the new features you need to open the _Settings_ dialog and check OneNote Tag import .
> 
> Let me know what you think?

Thanks，I'd like to try the beta version.

**Comment by WetHat** [comment]
@all-contributors add @JohnEricson for ideas

**Comment by WetHat** [comment]
Hi @zhongguocn,

Sure! You are very much welcome to try the beta version. You can get it here [SetupTaggingKitWiX.3.8.7607.24792.zip](https://github.com/WetHat/OnenoteTaggingKit/files/5458435/SetupTaggingKitWiX.3.8.7607.24792.zip)

**Comment by WetHat** [comment]
@all-contributors add @JohnEricson for test

**Comment by WetHat** [comment]
@all-contributors add @zhongguocn for test

**Comment by WetHat** [comment]
Fixed in this [feature release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.8.7617)
