### ISSUE TITLE
Feature Request: Adding a "copy pages" option to the results of tag search

### ISSUE THREAD

**Issue by osman1963** [WetHat/OnenoteTaggingKit#41]
First of all, thanks for the brilliant add-on

I was just wondering if it would be possible to add a 'copy pages' to the options available after doing a tag search. copy link to pages is available arleady, but being able to copy the pages them selves to another/new section would be really awsome and very helpful.

Thanks in advance

**Comment by WetHat** [comment]
Hi @osman1963 ,

the OneNote api does not support copying. The only way to implement that would be to retrieve the page content for each page and create new pages in the selected location. This is extremely inelegant and slow (the API representation of OneNote pages is XML text). Also, there might be some data loss related to attached files and handwritten notes.

**Comment by osman1963** [comment]
Aha.. I didn't know that. Thanks for the clarification and thanks again for making our lives easier 👍
