### ISSUE TITLE
[Enhancement] Text-Based Tag Entry

### ISSUE THREAD

**Issue by BrotherHawkins** [WetHat/OnenoteTaggingKit#43]
Use the OneNote Android app for notes on the go all the time. The app has bare minimal OneNote Tag support and I doubt MS plans many improvements.

Would be nice to have some way to enter a tokenized bit of text that could be converted to a Tag as soon as the page is loaded in the main OneNote app.

Something like: **otk::tagname**

**Comment by WetHat** [comment]
@BrotherHawkins you can add hashtags to page text and promote them to page tags with the OneNote desktop app. item 4 of the [Preferences Tab](https://github.com/WetHat/OnenoteTaggingKit/wiki/Preferences-Tab) documentation explains how to enable and use this feature. Does that work for you?
