### ISSUE TITLE
 Hope to save the search results in one page

### ISSUE THREAD

**Issue by zhongguocn** [WetHat/OnenoteTaggingKit#47]
The existing function is already very easy to use, but I hope to add a new function. 

I often search some tags combinations. I hope to maintain this search condition, save the search results in one page, and the content of the search results page will be updated automatically.

Can you add this function? 

thank you.

**Comment by zhongguocn** [comment]
Maybe we can achieve our goal in another way. 

When we set the search conditions of the tag, we get the search results. Save the page link of the search results in a page, add a refresh link at the top of the page, and then refresh the search results after the user clicks the link to replace the current page content with the latest results.

Would you please consider whether this method can be implemented? Thank you.

**Comment by WetHat** [comment]
Hi @zhongguocn,
 adding a refresh _link_ at the top of the page is not possible. Links on a page cannot trigger any actions in an Add-In. Howerver, there is a 'Refresh' button on the 'Tag Pages' dialog already which could be used to achieve something similar:

![image](https://user-images.githubusercontent.com/10697674/150751495-bdc51bda-c830-481b-a00c-5472bf70d487.png)

The process to create a saved search would then look like this:

* On the _Find Tagged Pages_ dialog there would be a 'Save Search' command  action to save the search result to a new page
   in the current section. 
  The page would look like this:
  
   ![image](https://user-images.githubusercontent.com/10697674/150754199-29f6b1c8-a384-498b-b240-26f4a7d0a551.png)

* To refresh the search result the _Refresh_ button on the  'Tag pages' dialog needs to be pressed..

Note: as long as the structure of the search result is left intact, any additional page content can be added before or after the
search result.

What do you think?

**Comment by zhongguocn** [comment]
Great. That's what I want. 
Do you plan to add this function to the next version?

can you add the management function of paragraph marks? Manage like page tags. That would be perfect.

BTW：Can you add the markdown function? Use the plug-in to track the changes of page content. 
For example, if the user enters "# headline", press enter to trigger the plug-in command, save the content in the page file and hide it. At the same time, it will be automatically replaced with "headline" of OneNote title text. 

If the user enters "headline" at the end of the paragraph"#tagA ", press enter to trigger the plug-in command, reduce the text of" # tagA "and automatically add" #tagA "to the paragraph tag.

Note：OneNote's page link supports URL protocol. Perhaps you can use the command OneNote taggingkit: / / commands to call the plug-in command.

**Comment by WetHat** [comment]
@zhongguocn,

      "Do you plan to add this function to the next version?"
Yes. The new version should be available Q1.

      "can you add the management function of paragraph marks? "
That is already in the current version. This functionality is described here:
* [Tagging a Page](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-a-Page) - Notes section at the bottom of tha page
* [Preferences](https://github.com/WetHat/OnenoteTaggingKit/wiki/Preferences-Tab) - Tag options section 4

      "Use the plug-in to track the changes of page content."
Unfortunately that is not possible. There are no events delivered to the add-in (technical limitation of the OneNote SDK). Therefore, any changes on the page require some manual action by the user. That is the reason  the _Refresh_ button on the _Tag Pages_ button is needed to sync paragraph tags and hashtags.

      "OneNote's page link supports URL protocol."
I know. However, that cannot be used to communicate with the add-in. OneNote will attempt to launch an external application. It would be conceivable to create an external application which then can  be registered as a protocol handler with the OS. That application would then be started on a click on that link and  would attempt to communicate with the add-in.
That would be quite complicated and expensive to implement. As long as the _Refresh_ button is acceptable it would rather not go that route.

**Comment by zhongguocn** [comment]
The current version already supports paragraph tag management! 

I missed it！

Where do you manage paragraph tagging? I can't find it.

**Comment by WetHat** [comment]
@zhongguocn, the management functionality for native OneNote tags is explained in item 4 of the numbered list in the [Preferences Tab](https://github.com/WetHat/OnenoteTaggingKit/wiki/Preferences-Tab) documentation. You would want to look for subsection __"Map OneNote Tags to Page Tags"__

**Comment by zhongguocn** [comment]
got it. You did a great job.Thanks！

The paragraph tag will not be updated until a tag is added。Can you make a button and click to update the paragraph tag? Or, a shortcut key is OK.

The paragraph tags are not managed by the OneNote Tagging Kit.Can OneNote tagging kit manage paragraph tags in the next version？

If you can manage paragraph tags with OneNote Tagging Kit and multiple paragraph tags search, it will be perfect.

**Comment by zhongguocn** [comment]
Mapped hashtags can be used in the Find Notes dialog for tag based refinement of the search result.

A little problem：Click search results cannot be linked to the paragraph。Can you fix it?

**Comment by WetHat** [comment]
@zhongguocn,
