### ISSUE TITLE
onedrive references in code

### ISSUE THREAD

**Issue by CptRude** [WetHat/OnenoteTaggingKit#58]
Hi, 

started already searching alternatives of OneNote caused by the lack of proper tagging capabilities but luckily found your project. Thank you for sharing this!
I quickly skimmed through your code and have a question: 
In the xml defined in OnenoteTaggingKit/OneNoteTaggingKit/find/FindTaggedPagesDesignerModel.cs line 21 (_strXml) you're referencing OneNote notebooks stored in onedrive. Is this on purpose? If yes - what is the purpose?

**Comment by WetHat** [comment]
Good catch @CptRude !
The class is used design time only by the VisualStudio UI designer and has no impact on production. Nevertheless, it should not use a link that pretends to point to a real notebook. The link made it there because of copy-paste laziness, so I'll fix this.
