### ISSUE TITLE
Mapping hashtags doesn't work with RTL tags

### ISSUE THREAD

**Issue by osman1963** [WetHat/OnenoteTaggingKit#59]
Hi,
Thanks for the awesome add-in.
Lately I migrated some files from Obsidian to OneNote, with their hashtag tags. The English ones were mapped just fine, however the Arabic ones didn't. Is there something I should do about it,  or  it is something that you could take care of?
Thanks in advance and have a lovely day :)

**Comment by WetHat** [comment]
@osman1963, looks like a bug. At this point there is nothing you can do.
