### ISSUE TITLE
Support for Windows 10 version

### ISSUE THREAD

**Issue by DonMendo** [WetHat/OnenoteTaggingKit#6]
Please considering supporting the free windows 10 OneNote version (Version 17.9001.21281.0 as in my laptop)

Thanks for your work.

**Comment by zhongguocn** [comment]
Microsoft will give up the desktop version and recommend the uwp version。
Please considering supporting the UWP OneNote version，thanks。

**Comment by emmacsmith92** [comment]
Hi, I am using OneNote for Office 365. I have downloaded your Tagging Kit, but it only seems to appear in OneNote 2016. Is there any way to get it to work in the newest OneNote?

Thanks,
Emma

**Comment by zhongguocn** [comment]
> Hi, I am using OneNote for Office 365. I have downloaded your Tagging Kit, but it only seems to appear in OneNote 2016. Is there any way to get it to work in the newest OneNote?
> 
> Thanks,
> Emma

Tagging kit is only supported by onenote2016, and the uwp version does not support plug-ins.

**Comment by WetHat** [comment]
The Universal App is no longer supported by Microsoft
