### ISSUE TITLE
Please release a new version.

### ISSUE THREAD

**Issue by yyangdid** [WetHat/OnenoteTaggingKit#60]
Thank you for this nice plugin for OneNote, Can you release a new version, the last version was a year ago.

**Comment by WetHat** [comment]
@yyangdid I'm working on it

**Comment by yyangdid** [comment]
Thank you 👍

**Comment by WetHat** [comment]
Done!

**Comment by yyangdid** [comment]
Thank you very much for your dedication, We have a easy-to-use plug-in. 💯
