### ISSUE TITLE
Latest Release doesn't show tags from previous versions

### ISSUE THREAD

**Issue by TheCarsino** [WetHat/OnenoteTaggingKit#62]
I've been working with an older version of the plugin. When I updated to the latest version I've lost a lot of tags and their relation to the pages.

Is this still a current problem on the newer versions? 

Also, where can I find the file or archive that stores the plugin pages?

Thanks

**Comment by WetHat** [comment]
Hi @TheCarsino,

>>When I updated to the latest version I've lost a lot of tags and their relation to the pages.<<
What does that mean? They no longer show up in search?

>>Also, where can I find the file or archive that stores the plugin pages?<<
The tags are stored as meta-information on each page.  There is no file. Therefore I do not understand what mean by 
'I've lost a lot of tags and their relation to the pages.

You might be missing the tags from the Tag Pages dialog. In that case just run a search once.

WetHat
WetHat

**Comment by WetHat** [comment]
Hi @TheCarsino,

The latest release build automatically recovers tags when the _Suggested Tags_ cache is empty or corrupted.

**Comment by TheCarsino** [comment]
Both solutions are pretty useful. Thanks!
