### ISSUE TITLE
Severe OneNote Tagging Kit Add-In Error

### ISSUE THREAD

**Issue by GH4TP** [WetHat/OnenoteTaggingKit#7]
I have installed the TaggingKit for the first time. The installation completed successfully. I opened ON2016 and clicked on a page to tag it. I then got an error as per attached. The log file also attached.

![tkerror](https://user-images.githubusercontent.com/38799710/40218509-cef20aea-5ab4-11e8-83b1-b4ab74f4b044.jpg)
[TKlog.log](https://github.com/WetHat/OnenoteTaggingKit/files/2015640/TKlog.log)

Need anything else?

Thanks, Tim

**Comment by WetHat** [comment]
Hi Tim,

thanks for the report. Looks like you tried to open the Tagging dialog at a location where there was no current OneNote page set. The log file indicates that the current OneNote page was not defined. The error looks a bit nasty, but the Add-In should work fine if you open a regular OneNote page and re-open the tagging dialog.

Let me know if that works for you.

Thanks, WetHat

**Comment by GH4TP** [comment]
Hi Peter, that's interesting. What do you you mean by a 'page set'? What does 'set' mean in this instance?

When I encountered the problem I made sure I placed my cursor on a page. On a number of tries it failed.  But technology is a strange beast. Today it works. And I can't recreate the problem.

You're right to close my ticket. Thank you and thank you for Tagging.
