### ISSUE TITLE
OneNote Add-In not loaded (A runtime error occured during the loading of the COM Add-in)

### ISSUE THREAD

**Issue by peterho2004** [WetHat/OnenoteTaggingKit#71]
I downloaded the add-in on 2 computers.  The first computer runs Office 365 (with latest channel update).  It works fine.
The second computer runs Office 2021 (OneNote® 2021 MSO Version 2202 Build 16.0.14931.20764 64-bit).  I was not able to get the add-in to load on the second computer.  (OneNote Add-In not loaded "A runtime error occured during the loading of the COM Add-in")  I have reinstalled/repaired the installation couple times.  (also tried the choco installation, no difference)  I also checked the .Net framework, it is up-to-date.  I also switched license from Office 2021 to Office 365, that also does not work (in the second machine).  I am not able to figure out what else to do.     Would you  have suggestions ?

**Comment by WetHat** [comment]
Hi @peterho2004 ,

You might wnat to try the troubleshooting steps in [Microsoft Office – Solutions for COM-Add-In not loading](https://accessdevtools.com/blog/microsoft-office-com-add-in-not-loading/). Loading errors have been reported very rarely. But when they occur they are difficult to fix.

WetHat
