### ISSUE TITLE
[Feature Request] Allow tagging directly within the text

### ISSUE THREAD

**Issue by muguu** [WetHat/OnenoteTaggingKit#8]
I'm using ZimWiki (https://github.com/jaap-karssenberg/zim-desktop-wiki) for years now as I found the tagging feature of OneNote quite inconvenient.

ZimWiki is flexible with tags. You can add a tag anywhere by just starting it with @
As a tag auto completion was missing, I programmed one, as well as a find / search tagged pages plugin :)

With your OneNoteTaggingKit I find myself re-considering OneNote again. I just wonder if a direct in-text tagging will be possible?

**Comment by WetHat** [comment]
Hi muguu,

Onenote already provides (somewhat inefficient) per-paragraph tagging. Handling tags anywhere within the text is outside the scope of this project unfortunately. In text tagging would cause a severe performance challenge with respect to tag search efficientcy and tag change management,

WetHat
