### ISSUE TITLE
Disconnect between Tag Pages and Find Pages Functions

### ISSUE THREAD

**Issue by toppinglift** [WetHat/OnenoteTaggingKit#93]
Hi Community and WetHat,

I am not a programmer, but I am an avid user of One Note and I admire the logical simplicity of ONTK especially when using the tags on the extensive database we have in OneNote.  The problem I am having is while the "Tag Pages" has all the tags I have inputted, the "Find Pages" does not carry all the latest tags I've inputted into the Tag Pages.  As a result, it cannot find those tags.  I have the latest version 5.1.8434.23617.  This is a really good program, but I do not understand why there is this disconnect between Tag and Find Tags--it should be pulling from the same database of tags I would think.  I hope you can help me, otherwise I will have to use a vastly inferior tagging system.  Thanks in advance.

**UPDATE 2-21-2023**--It appears I found a work around for the disconnect (at least for me).  I went into Settings-->Preferences and unchecked the box "Use Windows Search Service to find tagged pages."  I have no clue why this works, but once I unchecked the box, I could find all my tagged pages.  The box was checked by default.  Can anyone explain this?  Thanks.

**Comment by WetHat** [comment]
@toppinglift, the _Find Pages_ dialog uses _Windows Search Service_ to find tags quickly. There are following circumstances where you do not see the tags you applied with _Tag Pages in the _Find Pages_ dialog . 
* The _Windows Search Service_ is deactivated. Usually deactivating the _Windows Search Service_  is not a good idea. However,
   going into Settings-->Preferences and unchecking "Use Windows Search Service to find tagged pages" would work arraund that.
* The _Windows Search Service_ has not yet finished indexing the newly tagged pages when you opened the _Find Pages_ dialog. To make the new tags appear, wait a moment, and click on the [Refresh](https://wethat.github.io/OnenoteTaggingKit/v5.1/Usage/Search/Finding%20Notes.html#Dia-14) action of the _Find Pages_ dialog. In your case you forced the tags to appear by turning the _Windows Search Service_ integration off. This has performance  implications as described [here](https://wethat.github.io/OnenoteTaggingKit/v5.1/Support/Searching-pages-by-Tags-or-Full-Text-Queries-does-not-work.html).
* The tags where applied using the _Tag Pages_ dialog while the _Find Pages_  dialog was open. The _Find Pages_ dialog does not refresh tags automatically for performance reasons. To make the new tags appear click on the [Refresh](https://wethat.github.io/OnenoteTaggingKit/v5.1/Usage/Search/Finding%20Notes.html#Dia-14) action of the _Find Pages_ dialog. This re-runs a _Windows Search Service_ query for all page tags. After that all newly added tags should be available.

WetHat

**Comment by toppinglift** [comment]
Hi Wet Hat,

Thank you for your quick reply.  I followed your suggestions, but I am still getting inconsistent results using the Windows Search Service.  See attached screenshots of the same tag with 7 results (using the Windows Search Service) and 20 results (not using the Windows Search Service.)
![Screenshot with Windows Search Service](https://user-images.githubusercontent.com/63881713/220834715-23b6a981-1ae4-42ac-828e-4717c16ca454.jpg)
![Screenshot without Windows Search Service](https://user-images.githubusercontent.com/63881713/220834779-7a04d9cb-54f3-48b8-bb66-81eb60e771e9.jpg)

**Comment by WetHat** [comment]
@toppinglift , interesting! Could you actually click on the tag to apply the filter and check if the extra pages with _Windows Search Service_ off have anything in common?

  WetHat

**Comment by toppinglift** [comment]
Two identical pages, both under the tag "Con Ed Lighting."  Here is the "Find Tagged Pages" screen with the Use Windows Search Service **UNCHECKED.**  You will see both pages listed below as "2".

![image](https://user-images.githubusercontent.com/63881713/224800118-6f2bd5a8-9652-47a3-9869-a0fd6c368f09.png)

Now the same "Find Tagged Pages" screen with the Use Windows Search Service **CHECKED**.  This time I asked the "Find Tagged Pages" screen to find simply "Con Ed".  Note that it did not find the tag "Con Ed Lighting" as the first inquiry did with the box **UNCHECKED**.

![image](https://user-images.githubusercontent.com/63881713/224801673-71e0f326-d535-445f-ba2e-24c0d254f4ff.png)

**Comment by toppinglift** [comment]
Hi Wethat,

Do you have any further troubleshooting requests?

**Comment by WetHat** [comment]
Found a way to use the Windows Search Service for indexed pages and in addition detect and search in unindexed pages.
Fixed in this [release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v5.1.8514).
